version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always

  frontend:
      build: ./frontend
      ports:
        - "5173:5173"
      environment:
        - VITE_API_BASE_URL=http://localhost:8080
      restart: always
